package dis;

import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.Errors;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.ModelAndView;

@Controller
// This means that this class is a Controller
@RequestMapping(path = "/training")
public class TrainingController {
	@Autowired
	// This means to get the bean called userRepository
	// which is auto-generated by Spring, we will use it to handle the data
	private TrainingRepository trainingRepository;

	@RequestMapping
	public String main() {
		return "training";
	}

	@PreAuthorize("hasAnyRole('" + ProjectNames.ROLE_ADMIN + "','" + ProjectNames.ROLE_MANAGER + "', )")
	@GetMapping(path = "/add")

	public String createForm(Model model) {
		model.addAttribute("title", "Add a new Training");
		model.addAttribute("training", new Training());
		return "trainingAdd";
	}

	@PreAuthorize("hasAnyRole('" + ProjectNames.ROLE_ADMIN + "','" + ProjectNames.ROLE_MANAGER + "', )")
	@PostMapping(path = "/add")
	public ModelAndView createSubmit(@ModelAttribute @Valid Training training, Errors errors, Model model) {
		model.addAttribute("title", "Add a new Training");
		if (errors.hasErrors()) {

			return new ModelAndView("trainingAdd");

		}

		trainingRepository.save(training);
		return new ModelAndView("redirect:/training/all");

	}

	@PreAuthorize("hasAnyRole('" + ProjectNames.ROLE_ADMIN + "','" + ProjectNames.ROLE_MANAGER + "', )")
	@GetMapping(path = "/all")
	public ModelAndView readAll(Model model) {
		Iterable<Training> findAll = trainingRepository.findAllByOrderByName();
		model.addAttribute("title", "All Trainings");
		model.addAttribute("trainings", findAll);
		// this returns JSON or XML with the users
		// return departmentRepository.findAll();
		return new ModelAndView("trainingAll");
	}

	@PreAuthorize("hasAnyRole('" + ProjectNames.ROLE_ADMIN + "','" + ProjectNames.ROLE_MANAGER + "', )")
	@GetMapping(path = "/{id}")
	public String readById(@PathVariable("id") long id, Model model) {
		model.addAttribute("training", trainingRepository.findOne(id));
		// this returns JSON or XML with the department
		return "trainingById";

	}

	@PreAuthorize("hasAnyRole('" + ProjectNames.ROLE_ADMIN + "','" + ProjectNames.ROLE_MANAGER + "', )")
	// @ TODO
	@GetMapping(path = "/{id}/edit")
	public String createEdit(@PathVariable("id") long id, Model model) {
		// with input provided
		model.addAttribute("title", "Edit Training");
		model.addAttribute("training", trainingRepository.findOne(id));
		// this returns JSON or XML with the department
		return "trainingEdit";

	}

	@PreAuthorize("hasAnyRole('" + ProjectNames.ROLE_ADMIN + "','" + ProjectNames.ROLE_MANAGER + "', )")
	@PostMapping(path = "/{id}/edit", params = "edit=Delete")
	public ModelAndView createEditPostDelete(@PathVariable("id") long id, Model model) {
		Training findOne = trainingRepository.findOne(id);
		trainingRepository.delete(findOne);
		return new ModelAndView("redirect:/training/all");
	}

	@PreAuthorize("hasAnyRole('" + ProjectNames.ROLE_ADMIN + "','" + ProjectNames.ROLE_MANAGER + "', )")
	@PostMapping(path = "/{id}/edit", params = "edit=Save")
	public ModelAndView editForm(@PathVariable("id") long id, @ModelAttribute @Valid Training training, Errors errors,
			Model model) {

		if (errors.hasErrors()) {

			return new ModelAndView("trainingEdit");
		}
		// doin't create new object here, read old one by id and update its properties
		Training dbTraining = trainingRepository.findOne(id);
		// update the properties with values comming from model
		dbTraining.setName(training.getName());
		dbTraining.setDuration(training.getDuration());
		dbTraining.setVersion(training.getVersion());
		// then save(update) to database
		trainingRepository.save(dbTraining);
		return new ModelAndView("redirect:/training/all"); // and choose template to kick in afterwards
		// and choose template to kick in afterwards
		// and then add another method that also catches the action of deleting and
		// removes instead
		// keep in mind that you may be forced to change this one to catch the action
		// type "submit" or "save" or something like this

	}

	@PreAuthorize("hasAnyRole('" + ProjectNames.ROLE_ADMIN + "','" + ProjectNames.ROLE_MANAGER + "', )")
	@RequestMapping(path = "/delete/{id}")
	public ModelAndView createEdit(@ModelAttribute Training training, Model model) {
		Training findOne = trainingRepository.findOne(training.getId());
		trainingRepository.delete(findOne);

		return new ModelAndView("redirect:/training/all");
	}
}
